### ISSUE TITLE
Integer is too small for size field

### ISSUE THREAD

**Issue by kabzo** [Roche/lxdhub#111]
Some images are large, and the actual image size does not fit  into`integer` in https://github.com/Roche/lxdhub/blob/master/packages/db/src/models/image.entity.ts#L28 

The original error was: 
```
db_1      | 2019-08-20 12:54:56.642 UTC [73] ERROR:  value "2509016255" is out of range for type integer
```

After changing `integer` to `bigint` I get error: `[LXDHubAPI] error: Expected a finite number, got string: 2509016255`

Do you know why? 

Thanks

**Comment by BrunnerLivio** [comment]
Thanks a lot for reporting! 

`BigInt`s are a "newer" thing in the Node.js world and it seems like the ORM we have used for LXDHub does not really work nicely with it as of today. See [typeorm/typeorm#2400](https://github.com/typeorm/typeorm/issues/2400#issuecomment-442272052). I think the ORM just converts it to a string, because before `BigInt` was a thing in JS, that was the way to go. Therefore it leads to these strange error messages.

Let me find a fix for that :)

**Comment by kabzo** [comment]
Thanks @BrunnerLivio !

**Comment by kabzo** [comment]
@BrunnerLivio I tried it but it did not work unfortunately

**Comment by BrunnerLivio** [comment]
Should be fixed now - can you check? :)

**Comment by kabzo** [comment]
@BrunnerLivio works! Thanks
